version: "3.9"
name: PROJEKS_AKSO_SATYA&HAKEEM

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    configs:
      - source: custom_nginx_conf
        target: /etc/nginx/nginx.conf

  mysql_db:
    image: mysql:latest
    container_name: TUGAS_AKSO_SATYA$HAKEEM
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8002:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql_db
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app_network:
    driver: bridge

volumes:
  db_data:

configs:
  custom_nginx_conf:
    file: ./nginx2/nginx.conf
